name: python application test with github actions
on: [push]
jobs:
  build:
    runs-on:ubuntu-latest
    steps:
    - uses: acions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version:3.10
    - name: install dependencies
      run: |
       make install
    - name: Lint with pylint
      run: |
       #make lint
    - name Test wih pytest
      run: |
       #make test
    - name: Format code
      run: |
        #make format
